servers:
# Fires a REST request to https://localhost:8443/rest/api/latest/result.json?os_authType=basic&expand=results.result to get latest test results
  - displayName: Local Bamboo
    host: localhost
    port: 8443
    useSSL: true
    username:
    #Provide password or passwordEncrypted and encryptionKey
    password:
    passwordEncrypted:


encryptionKey:

# number of concurrent tasks
numberOfThreads: 5

connection:
  socketTimeout: 2000
  connectTimeout: 2000
  sslCertCheckEnabled: false
  sslVerifyHostname: false
  sslProtocols: ["TLSv1"]

taskSchedule:
  numberOfThreads: 1
  # Fires REST api every taskDelaySeconds seconds and caches the results to display every minute
  taskDelaySeconds: 120


#prefix used to show up metrics in AppDynamics 
metricPrefix: "Custom Metrics|Bamboo|"